# Generated by Django 2.2.5 on 2019-12-28 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.CharField(max_length=5)),
                ('unit_of_temperature', models.CharField(choices=[('F', 'Fahrenheit'), ('C', 'Celsius')], max_length=1)),
            ],
        ),
    ]
